# set some local variables to make this easier to read
set(EMULATOR "${CMAKE_ARGV7}")
set(TESTPROGRAM "${CMAKE_ARGV5}")
set(INPUTFILE "${CMAKE_ARGV6}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy "${TESTDIR}/${INPUTFILE}" "${INPUTFILE}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E rm "${INPUTFILE}.cpp")
if (EMULATOR)
    message(STATUS "about to execute: \"${EMULATOR}\" \"${TESTPROGRAM}\" -o \"${INPUTFILE}\"")
    execute_process(COMMAND "${EMULATOR}" "${TESTPROGRAM}" -o "${INPUTFILE}")
else()
    message(STATUS "about to execute: \"${TESTPROGRAM}\" -o \"${INPUTFILE}\"")
    execute_process(COMMAND "${TESTPROGRAM}" -o "${INPUTFILE}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files --ignore-eol "${TESTDIR}/${INPUTFILE}.cpp" "${INPUTFILE}.cpp")
